version: "2"
services:
  homer:
    image: b4bz/homer
    container_name: homer
    volumes:
      - /mnt/Pool4Configs/DockerConfigs/Homer:/www/assets
    ports:
      - 8080:8080
    #environment:
    #  - UID=1000
    #  - GID=1000
    restart: unless-stopped

  transmission-openvpn:
        image: haugene/transmission-openvpn
        container_name: Transmission
        cap_add:
            - NET_ADMIN
        volumes:
            - '/mnt/Pool4Configs/DockerConfigs/Transmission/:/config'
            - '/mnt/Downloads/Transmission/:/data'
        environment:
            - OPENVPN_PROVIDER=PIA
            - OPENVPN_CONFIG=sweden
            - OPENVPN_USERNAME=p1679432
            - OPENVPN_PASSWORD=GC37VMX6n5
            - LOCAL_NETWORK=192.168.0.0/16
            - TRANSMISSION_WATCH_DIR_FORCE_GENERIC=true
            - TRANSMISSION_WEB_UI=flood-for-transmission
            - TRANSMISSION_DHT_ENABLED=false
            - TRANSMISSION_PEX_ENABLED=false
            - TRANSMISSION_HOME=/config
            - TZ=NO
        ports:
            - '9091:9091'
        restart: unless-stopped
        network_mode: bridge
        logging:
            driver: json-file
            options:
                max-size: 10m
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: bridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /home/dm/configs/Sonarr/:/config
      - /mnt/Pool1Media:/tv #optional
      - /mnt/Downloads/Transmission:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped

  jackett:
      image: lscr.io/linuxserver/jackett:latest
      container_name: jackett
      network_mode: bridge
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Etc/UTC
        - AUTO_UPDATE=true #optional
        - RUN_OPTS= #optional
      volumes:
        - /home/dm/configs/Jackett/:/config
        - /mnt/Downloads/Transmission/Watch:/downloads
      ports:
        - 9117:9117
      restart: unless-stopped
